# 转载指定视频到Bilibili

name: 转载视频

on:
  workflow_dispatch:
    inputs:
      url:
        description: '视频链接 (Youtube/Twitch/pixiv 等 yt-dlp 支持链接)'
        required: true
        default: ''
      title:
        description: '标题格式 (如：[转载][{uploader}]{title})'
        required: true
        default: '{title}'
      desc:
        description: '描述格式 (如：{desc})'
        required: true
        default: '{desc}'
      tags:
        description: '视频标签 (半角逗号隔开)'
        required: true
        default: '转载'      
      thread:
        description: '视频分区'
        required: true
        type: choice
        options:
         
         - 野生技术协会/122
         - 教程演示/127
         - 科学·探索·自然/178
         - 科技·软件应用/2230 
      opts:
        description: '其他设置 (如:--original --no-reprint)'
        required: false
        default: ''
      ydl_opts:
        description: 'yt-dlp 设置 (默认设置使用 aria2 下载,遇到限流可考虑添加 format=best)'
        required: false
        default: 'external_downloader=aria2c'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt  
        sudo apt-get install aria2
    - name: Begin Reuploading      
      env:     
        SESSION : ${{ secrets.SESSION }}
        SESSION_UPLOAD : ${{ secrets.SESSION_UPLOAD }}
        SESSION_SUBMIT : ${{ secrets.SESSION_SUBMIT }}
             
      run: |
        python -m bilibili_toolman --load "$SESSION" `[[ ! -z "$SESSION_UPLOAD" ]] && echo "--load_upload \"$SESSION_UPLOAD\""` `[[ ! -z "$SESSION_SUBMIT" ]] && echo "--load_submit \"$SESSION_SUBMIT\""` --http --cdn ws --youtube "${{ github.event.inputs.url }}" --title "${{ github.event.inputs.title }}" --desc "${{ github.event.inputs.desc }}" --tags "${{ github.event.inputs.tags }}"  --thread_id `echo ${{ github.event.inputs.thread }} | cut -d/ -f2` ${{ github.event.inputs.opts}} --opts "${{ github.event.inputs.ydl_opts }}"
